### PR TITLE
WIP: ISPs page improvements

### PR DESCRIPTION
**Pull request by RotationMatrix**
This PR aims to implement the improvements from [tpo/community#72](https://dip.torproject.org/torproject/web/community/issues/72).

## To Do
- [x] Add table of contents (or countries)
- [x] Add link anchors for countries
- [ ] Metrics queries
- [ ] Squash commits

About link anchors, I was hoping to put them on the same line as the country name. Unfortunately, markdown links and headers don't nest well. The header `id` changes when the link is added, which breaks the link.

This:
```
### [Austria](#austria)
```
Becomes:
```html
<h3 id="[austria]-austria">
  <a href="#austria">Austria</a>
</h3>
```

If these are not translated strings, we could embed the headers as raw HTML. \*cringes\*
Alternatively, they could fit below the table headers or use a custom model with some magic under the hood. Any suggestions?

### CODE REVIEW

**Comment by RotationMatrix** [comment]
Updated to mimic the link style on [metrics.tpo](https://metrics.torproject.org/about.html#ecosystem).

It still relies on raw HTML in the `contents.lr`. Would like to find a way to use normal markdown if possible.

**Comment by mpguerra** [comment]
Have you considered using databags to hold the ISP details? e.g similar to the way it's done in [onions.ini](https://github.com/torproject/community/blob/master/databags/onions.ini)

Then you can use a template to render the details in the ini file, e.g as in https://github.com/torproject/community/blob/master/templates/onion-services.html#L39-L52

**Comment by RotationMatrix** [comment]
I had not thought of that. It would also make the rows of information easier to read and parse.

**Comment by RotationMatrix** [comment]
Can't believe how much time is flying by.

I've been playing around with the databags idea. So far my only concerns are:
- File size if we include all ISPs. Just the US ISPs fills 420 lines in an INI file.
- Translation of the `comments` field. Being just one field, it might be difficult to translate one sentence at a time like the rest of tpo.

```ini
[2HOST]
country="United States"
homepage=https://2host.com/
asn=null
allows_bridges="Yes"
allows_relays="Yes"
allows_exits="Yes(?)"
comments="Vague AUP/Abuse handling"
last_updated="2014-10-15"
```

Also to make sure I'm heading in the right direction. We want to be able to merge the old ISPs page from trac with insights from metrics.tpo and make the whole thing machine readable so others can build off the data, right?

**Comment by gusgustavo** [comment]
> Can't believe how much time is flying by.
> 

I know right!

> I've been playing around with the databags idea. So far my only concerns are:
> 
>     * File size if we include all ISPs. Just the US ISPs fills 420 lines in an INI file.
> 

What if we also split the files by countries in a directory? So US, FR, DE, NL would be huge, but all the others would be ok to manipulate?

We could also merge "allows_bridge" and "allows_relays" into "allows_non_exits".

>     * Translation of the `comments` field. Being just one field, it might be difficult to translate one sentence at a time like the rest of tpo.
> 

Right now the `comments` field is nice to have on a wiki page, but they might not worth to migrate to the portal since many of them are very outdated.

> 
> ```ini
> [2HOST]
> country="United States"
> homepage=https://2host.com/
> asn=null
> allows_bridges="Yes"
> allows_relays="Yes"
> allows_exits="Yes(?)"
> comments="Vague AUP/Abuse handling"
> last_updated="2014-10-15"
> ```
> 
> Also to make sure I'm heading in the right direction. We want to be able to merge the old ISPs page from trac with insights from metrics.tpo and make the whole thing machine readable so others can build off the data, right?

Right!

**Comment by gitbugged** [comment]
Probably not the right place for this, but how is one to contribute anonymously to this list? I had a very bad recent ISP experience for merely running a non-exit relay and am no longer able to add it to [trac](https://trac.torproject.org/projects/tor/wiki/doc/GoodBadISPs) using the anonymous `cypherpunk` account. 

In addition, I am unable to signup on the new Tor [gitlab](https://gitlab.torproject.org/users/sign_in#register-pane) instance. (Registration is disabled?) 

Using Github for Tor development is a very bad idea from both an [free software](https://www.fsf.org/news/gnu-releases-ethical-evaluations-of-code-hosting-services) and anonymity perspective. I hope that this will be resolved in the near future. Whoever posted the final complaint on [#31063](https://trac.torproject.org/projects/tor/ticket/31063#comment:4) prior to it going read-only is correct. Having [FVEY](https://en.wikipedia.org/wiki/FVEY) approved e-mail providers as barrier to signup is a major blockage to entry and development.

**Comment by emmapeel2** [comment]
> Probably not the right place for this, but how is one to contribute anonymously to this list? I had a very bad recent ISP experience for merely running a non-exit relay and am no longer able to add it to [trac](https://trac.torproject.org/projects/tor/wiki/doc/GoodBadISPs) using the anonymous `cypherpunk` account.

Sorry about that. Can you please try reporting it with anonticket? https://anonticket.onionize.space/ . It is an interface that tries to emulate the use of the cypherpunks account.

**Comment by RotationMatrix** [comment]
Closing this PR for now. I haven't been able to commit enough time to finishing it. Anyone is welcome to build off of it if they find it useful.

**Pull request closed without merging**
