### PR TITLE
[Relay] Assigned keys

### PR DESCRIPTION
**Pull request by SehrishHussain**
Assigned keys in alphabetical order to:

- **CentOS/RHEL** key: 1
- **Debian/Ubuntu** key: 2
- **DragonflyBSD** key: 3
- **FreeBSD** key: 5
- **NetBSD** key: 6
- **OpenBSD** key: 7

### CODE REVIEW

**Comment by SehrishHussain** [comment]
@gusgustavo take a look. Please leave feedback.

**Comment by gusgustavo** [comment]
@SehrishHussain please squash your commits.

**Comment by SehrishHussain** [comment]
@gusgustavo haven't I squashed and force-pushed already above?

**Comment by gusgustavo** [comment]
Nope, I can see 13 commits here: https://github.com/torproject/community/pull/126/commits and should be only one.

**Comment by SehrishHussain** [comment]
@gusgustavo So, it shows I have committed to changes made by other authors (I don't remember committing those)



now


Here I squashed all MY commits into one. Should i squash all the other 13 commits too? (I didn't authored)

nowt

**Comment by gusgustavo** [comment]
The issue here is that you're pushing other commits to your branch. Please remove these commits and push only the right commit, so I can merge to master. Thanks!

**Comment by SehrishHussain** [comment]
@kulsoomzahra hi, can you help me out here? So, I tried to delete all the unnecessary commits and push the desired one [commit](https://github.com/torproject/community/pull/126/commits/d56163b264be98785a03da4d60b8a9ed0981f1e5). Everytime I push my changes extra commits appear. Check my latest commit. Please leave feedback.

**Comment by kulsoomzahra** [comment]
@SehrishHussain hi, sure. I can see 7 commits here. You're supposed to squash your commits , doing so will result in only 1 commit. 

`pick commit 1
 pick commit 2
 pick commit 3`

Change `pick` to `squash` in the last 2 commits. This will squash your commits (Note: This is for 3 commits only, you'll need to do this for 7)

**Comment by SehrishHussain** [comment]
@kulsoomzahra I have squashed some 13 commits so far, they keep on adding. I pulled all the changes from remote branch to my local repo. It is causing extra commits to appear. If I dont pull the changes, git tells me my local repo is x commits behind remote repo. Anyway thank you for your feedback. :)

**Comment by gusgustavo** [comment]
@SehrishHussain if git squashing is causing a lot of extra work, it's fine to open a new pull request (with only one commit) too.

**Comment by emmapeel2** [comment]
ok, i merged it with 5485d139c88a11387caacc4f7465911520f5b75a

this merge request can be closed

**Comment by gusgustavo** [comment]
Thank you @emmapeel2!

**Pull request closed without merging**
