### PR TITLE
Changed unordered list to ordered list in instructions.

### PR DESCRIPTION
**Pull request by LilyLME**
The steps followed to sign up on Transifex to become a Tor translator would be nice to be an ordered list, so that the reader follows them chronologically.

### CODE REVIEW

**Comment by LilyLME** [comment]
@emmapeel2 , @gusgustavo

**Comment by mpguerra** [comment]
LGTM, the one nit I would have is whether we want `1.` for all the entries or whether we actually want to add the correct numbers, e.g `1.`, `2.` for each of the lists. What do you think @emmapeel2 ?

**Comment by LilyLME** [comment]
> LGTM, the one nit I would have is whether we want `1.` for all the entries or whether we actually want to add the correct numbers, e.g `1.`, `2.` for each of the lists. What do you think @emmapeel2 ?

Okay @mpguerra . I read somewhere that 1. is better than using the correct numbers for each of the list,because more steps could be added in future,and it will just require including that new step on the correct line and add a 1. in front of it. I dont know if you get what i am trying to say?

**Comment by mpguerra** [comment]
> > LGTM, the one nit I would have is whether we want `1.` for all the entries or whether we actually want to add the correct numbers, e.g `1.`, `2.` for each of the lists. What do you think @emmapeel2 ?
> 
> Okay @mpguerra . I read somewhere that 1. is better than using the correct numbers for each of the list,because more steps could be added in future,and it will just require including that new step on the correct line and add a 1. in front of it. I dont know if you get what i am trying to say?

Yup, I thought that's why you might have done it. I don't have a strong opinion about it myself which is why I wanted a second one :)

**Comment by LilyLME** [comment]
> > > LGTM, the one nit I would have is whether we want `1.` for all the entries or whether we actually want to add the correct numbers, e.g `1.`, `2.` for each of the lists. What do you think @emmapeel2 ?
> > 
> > 
> > Okay @mpguerra . I read somewhere that 1. is better than using the correct numbers for each of the list,because more steps could be added in future,and it will just require including that new step on the correct line and add a 1. in front of it. I dont know if you get what i am trying to say?
> 
> Yup, I thought that's why you might have done it. I don't have a strong opinion about it myself which is why I wanted a second one :)

Hey @mpguerra, I noticed these changes have been made here https://community.torproject.org/localization/becoming-tor-translator/  but my PR wasnt merged. How so?

**Comment by mpguerra** [comment]
> > > > LGTM, the one nit I would have is whether we want `1.` for all the entries or whether we actually want to add the correct numbers, e.g `1.`, `2.` for each of the lists. What do you think @emmapeel2 ?
> > > 
> > > 
> > > Okay @mpguerra . I read somewhere that 1. is better than using the correct numbers for each of the list,because more steps could be added in future,and it will just require including that new step on the correct line and add a 1. in front of it. I dont know if you get what i am trying to say?
> > 
> > 
> > Yup, I thought that's why you might have done it. I don't have a strong opinion about it myself which is why I wanted a second one :)
> 
> Hey @mpguerra, I noticed these changes have been made here https://community.torproject.org/localization/becoming-tor-translator/ but my PR wasnt merged. How so?

Hi, this was merged here: https://gitweb.torproject.org/project/web/community.git/commit/?id=7c7daf97db0a30f224a2d6af6cbeaefd0412b25e 

We can't merge on GitHub directly due to the fact that this repo on GitHub is a mirror and if we merge here directly, your changes would have been overwritten by any other merges on the main git repo. 

Rest assured that the merge has been done under your name :)

**Pull request closed without merging**
